### PR TITLE
Make private: yes/no working

### PR DESCRIPTION
**Pull request by grisuthedragon**
It seems, the `private` attribute was somehow a dummy, I changed this to the following behaviour:

Now, private: yes means, it is my private thing
and private: no means, everybody with hinkskalle access can see it.

### CODE REVIEW

**Comment by h3kker** [comment]
This breaks the tests: https://testha.se/knecht/csf-ngs/hinkskalle/109/backend-report.html

I'm not 100% sure what my intended semantics were here. At least once before I panicked about the private flag and introduced something similar, just to realise afterwards that no, actually I wanted it to be that way. I'll look into it later.

**Comment by grisuthedragon** [comment]
Not problem. My first test users saw the private flag and try to share single collections from their name space and then, I realized the by now, the `private` flag was only a dummy.

**Comment by h3kker** [comment]
No, not a dummy. There is intention behind the current behaviour: You can **never** browse containers/collections of other users; but pull the images if you knew the library URL, except if they were `private`. 

The `defaultPrivate` flag on the entity presets the `private` flag on the collections, which in turn presets the `private` flag when you create new containers within the collection, ie. containers in private collections will always be created private, hence images could not be pulled by others (unless you explicitly unset it)

For shared collections I added the groups feature: Create a group, it will get its own entity. E.g. testhasenstall. Within that all members of the group Testhasenstall can create, browse, ... collections and containers (depending on their role: readonly or contributor). The private flag applies within that as well, *except* that members of the group still have access to the images.

**Comment by grisuthedragon** [comment]
Ahh, ok then it seems that we have a slightly different understanding on what "private" means. That was unclear to me and my buddies. Our first intention about "private" yes or no, was if other logged in people can see and use it or not.  I think that was grown from your use-case, which let you develop hinkskalle.  We mostly think in the visibility style of gitlab, having public ( all, even without login), internal (all with a login), private ( a user and people/groups selected by the user).

**Comment by h3kker** [comment]
I definitely need to document that better :(

**Comment by grisuthedragon** [comment]
But since we're thinking of two different private styles, I close this request.

**Pull request closed without merging**
